### ISSUE TITLE
MethodError during call to isnan in julia 0.5.2 and 0.6.1

### ISSUE THREAD

**Issue by pegger0709** [JuliaPlots/VennEuler.jl#18]
Hello,
I installed the VennEuler package, then followed the example given on the repository. Everything worked fine until I ran the line

`eo = make_euler_object(setlabels, randdata, spec, sizesum=.5) # test shortcut`

at which point the following error

`ERROR: MethodError: no method matching isnan(::Array{Array{Float64,1},1})`

was thrown. It seems to be on line 79 and 80 of src/states.jl. I tried on both julia 0.5.2 and julia 0.6.1 and got the same result.

Thanks for looking into this and best regards,

Philip

**Comment by HarlanH** [comment]
Hi Philip -- yes, the package has sadly been broken for a while. I'm hoping
to make time to take a look once Julia 1.0 lands, but until then, you're
probably on your own...
