### ISSUE TITLE
transfer to JuliaPlots organization ?

### ISSUE THREAD

**Issue by bjarthur** [JuliaPlots/VennEuler.jl#21]
... to improve findability, and let the community maintain it if you not longer have time.

**Comment by HarlanH** [comment]
Hi, happy to do this! I haven't had time to do any Julia work in a year or two, and it's unlikely that'll change. 

I suspect that it should be possible to get some pretty substantial speedups in this package, with some clever profiling and optimization. And the code is a little Julia 0.3 in style...

What do I need to do to make the transfer?

**Comment by bjarthur** [comment]
@mkborregaard  what do you think of transferring VennEuler.jl over to JuliaPlots?  it's a great package, but needs a little love.  i've got a [PR](https://github.com/HarlanH/VennEuler.jl/pull/17) to upgrade it to julia 0.6, and once that merges i'll start working on 0.7.

**Comment by mkborregaard** [comment]
@simondanisch and @daschw own JuliaPlots now, so that question should be for them.
But to be honest I'd be a little concerned with 

> let the community maintain it if you not longer have time

Try to have a look at the number of open issues on Plots.jl for instance...

**Comment by bjarthur** [comment]
i'm volunteering to maintain it

**Comment by bjarthur** [comment]
@simondanisch @daschw what do you think about transferring VennEuler.jl to the Plots org and assigning me as the maintainer?  this a valuable part of the julia ecosystem that needs updating to 1.0

**Comment by daschw** [comment]
Sure. I never transfered a package. Could anyone explain to me how to do this?

**Comment by HarlanH** [comment]
It looks like I could do so myself if I had specific permissions in the
JuliaPlots org.  https://github.com/HarlanH/VennEuler.jl/settings/transfer
 says:

Transfer ownership

Transfer this repository to another user or to an organization where you
have the ability to create repositories.

Could someone give me permission to do so in JuliaPlots?

**Comment by HarlanH** [comment]
Done!
